### ISSUE TITLE
forceQueryable needed in GsfProxy Android Manifest for Some Apps to Register for FCM Push Notifications

### ISSUE THREAD

**Issue by CircuitSerialKiller** [microg/android_packages_apps_GsfProxy#17]
### Transferring the issue here:
https://github.com/microg/GmsCore/issues/2009
to the correct repository - GsfProxy. See original link for more details and temporary workaround. 

This is due to app visibility changes in Android 11+ 
https://developer.android.com/training/package-visibility

This was addressed in GmsCore, but not in GsfProxy
https://github.com/microg/GmsCore/issues/1409

Request to please add

android:forceQueryable="true"
under <application
in AndroidManifest.xml
here
https://github.com/microg/GmsCore/blob/master/play-services-core/src/main/AndroidManifest.xml
and publish a new signed release.

### Sample logcat for com.hikvision.hikconnect

08-13 17:49:03.818 818 818 W System.err: android.content.pm.PackageManager$NameNotFoundException: com.google.android.gsf
08-13 17:49:03.818 818 818 W System.err: at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:211)
08-13 17:49:03.818 818 818 W System.err: at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:183)
08-13 17:49:03.818 818 818 W System.err: at com.hikvision.hikconnect.push.fcm.FcmPushClient.checkGoogleDevice(SourceFile:2)
08-13 17:49:03.818 818 818 W System.err: at com.hikvision.hikconnect.push.fcm.FcmPushClient.isSupport(SourceFile:1)
08-13 17:49:03.818 818 818 W System.err: at com.hikvision.hikconnect.push.client.HcPushClientManager.tryInitPushClient(SourceFile:1)
08-13 17:49:03.818 818 818 W System.err: at com.hikvision.hikconnect.push.client.HcPushClientManager.startDispatchClient(SourceFile:7)
08-13 17:49:03.818 818 818 W System.err: at com.hikvision.hikconnect.push.client.HcPushClientManager.(SourceFile:14)
08-13 17:49:03.818 818 818 W System.err: at com.hikvision.hikconnect.push.impl.HcClientManagerImpl.initPush(SourceFile:2)
08-13 17:49:03.818 818 818 W System.err: at com.hikvision.hikconnect.app.App.onCreate(SourceFile:255)
08-13 17:49:03.818 818 818 W System.err: at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1208)
08-13 17:49:03.818 818 818 W System.err: at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7006)
08-13 17:49:03.818 818 818 W System.err: at android.app.ActivityThread.access$1800(ActivityThread.java:274)
08-13 17:49:03.818 818 818 W System.err: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2104)
08-13 17:49:03.818 818 818 W System.err: at android.os.Handler.dispatchMessage(Handler.java:106)
08-13 17:49:03.818 818 818 W System.err: at android.os.Looper.loop(Looper.java:233)
08-13 17:49:03.818 818 818 W System.err: at android.app.ActivityThread.main(ActivityThread.java:8030)
08-13 17:49:03.818 818 818 W System.err: at java.lang.reflect.Method.invoke(Native Method)
08-13 17:49:03.818 818 818 W System.err: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
08-13 17:49:03.818 818 818 W System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by ale5000-git** [comment]
Hi,
this should already be fixed but there isn't a new version of GsfProxy yet.

**Comment by ale5000-git** [comment]
@CircuitSerialKiller
Could you please try it and see if it fix the problems?

**Comment by CircuitSerialKiller** [comment]
@ale5000-git I just packaged it up and installed it. I cleared storage for Hik-Connect, ran Hik-Connect, and successfully got prompted by microG to allow registration. Push notifications are working from the app as well. Everything else seems to be working fine. Thanks for fixing this!

**Comment by CircuitSerialKiller** [comment]
Just a note for anyone using a ROM with microG built in. The updated GsfProxy mentioned above hasn't been added to the official releases, so you would need to use a Magisk module to replace it, then after rebooting, also install the apk as a user app so the the packages.xml file gets updated foreceQueryable value. 

Magisk module for ROMs like LineageOS with microG in /product/app/GsfProxy

[GSFProxy-With-forceQueryable-ProductFolderMagiskModule.zip](https://github.com/user-attachments/files/25062553/GSFProxy-With-forceQueryable-ProductFolderMagiskModule.zip)

Thanks again to everyone who's contributed to microG!

**Comment by ale5000-git** [comment]
Currently there isn't a new official version, but there is a version signed by me here: https://github.com/micro5k/microg-unofficial-installer/blob/main/zip-content/origin/priv-app/GsfProxyA5K.apk
