### ISSUE TITLE
services out of date

### ISSUE THREAD

**Issue by theScrabi** [microg/android_packages_apps_GsfProxy#3]
Hello,

I've installed fakeGApps, and did everything to satisfy microg, but still [push notification tester](https://play.google.com/store/apps/details?id=com.firstrowria.pushnotificationtester) tels me i should uppdate gservices.

[<img src="https://cloud.githubusercontent.com/assets/1891273/20620275/4113b782-b2f9-11e6-8740-9459df2d5d8c.png" width=120>](https://cloud.githubusercontent.com/assets/1891273/20620275/4113b782-b2f9-11e6-8740-9459df2d5d8c.png)
[<img src="https://cloud.githubusercontent.com/assets/1891273/20620277/443e427e-b2f9-11e6-9a71-b4db0d44c372.png" width=120>](https://cloud.githubusercontent.com/assets/1891273/20620277/443e427e-b2f9-11e6-9a71-b4db0d44c372.png)

What went wrong?

rgds scahbi

**Comment by theScrabi** [comment]
All right found out this:
 Here in [line21](http://pastebin.com/vVQaRjtN) it says play services were outdated:
`11-25 10:50:51.363 15424 15424 W GooglePlayServicesUtil: Google Play services out of date.  Requires 9452000 but found 9258259`

**Comment by ale5000-git** [comment]
It isn't related to this component but to [this](https://github.com/microg/android_packages_apps_GmsCore).

Plus it will already work if you update it to 0.2.4-28

**Comment by theScrabi** [comment]
All right.

**Comment by Lanchon** [comment]
i confirm issue and fix: you have to use latest unstable release.
